- name: Deploy JFrog Artifactory, configure efs
  hosts: all
  become: true
  roles:
    - artifactory
    - efs
    - cloudwatch_agent

#- nams: Configure CloudWatch Agent
#  hosts: all
#  become: yes
#  roles:
#    - cloudwatch_agent
